# Generated by Django 5.1.2 on 2024-11-05 13:54

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_fam', models.CharField(default='', max_length=100, verbose_name='Фамилия')),
                ('user_name', models.CharField(default='', max_length=100, verbose_name='Имя')),
                ('user_otc', models.CharField(default='', max_length=100, verbose_name='Отчество')),
                ('user_fullname', models.CharField(default='', max_length=200, verbose_name='ФИО')),
                ('user_phone', models.CharField(default='', max_length=20, verbose_name='Тел.')),
                ('user_email', models.CharField(default='', max_length=50, unique=True, verbose_name='Почта')),
            ],
        ),
        migrations.CreateModel(
            name='Coords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(verbose_name='Ширина')),
                ('longitude', models.FloatField(verbose_name='Долгота')),
                ('height', models.IntegerField(verbose_name='Высота')),
            ],
        ),
        migrations.CreateModel(
            name='PerevalAreas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_parent', models.IntegerField()),
                ('title', models.CharField(max_length=100, verbose_name='Наименование')),
            ],
        ),
        migrations.CreateModel(
            name='StatusList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.IntegerField()),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Наименование')),
            ],
        ),
        migrations.CreateModel(
            name='PerevalAdded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime(2000, 1, 1, 0, 0), verbose_name='Дата')),
                ('beauty_title', models.CharField(default='', max_length=20, verbose_name='Вид объекта')),
                ('title', models.CharField(default='', max_length=100, verbose_name='Наименование')),
                ('other_titles', models.CharField(default='', max_length=124, verbose_name='Другие наименования')),
                ('connect', models.CharField(default='', max_length=100, verbose_name='Что соединяет')),
                ('level_winter', models.CharField(default='', max_length=10, verbose_name='зима')),
                ('level_summer', models.CharField(default='', max_length=10, verbose_name='лето')),
                ('level_autumn', models.CharField(default='', max_length=10, verbose_name='осень')),
                ('level_spring', models.CharField(default='', max_length=10, verbose_name='весна')),
                ('coords', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='pereval_app.coords')),
                ('users', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='pereval_app.authors')),
                ('obj_status', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='pereval_app.statuslist')),
            ],
        ),
        migrations.CreateModel(
            name='PerevalImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_data', models.CharField(max_length=1024, verbose_name='Картинка')),
                ('image_title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('image_go', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pereval_app.perevaladded')),
            ],
        ),
    ]
